/*
 * Copyright (C) 2022 Julio
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package instituto.gui;

import instituto.data.controladdores.Controlador;
import instituto.data.modelos.TipoUsuario;
import instituto.data.modelos.Usuario;
import javax.swing.JOptionPane;
import static instituto.data.modelos.TipoUsuario.ADMINISTRACION; //probar

/**
 *
 * @author Julio
 */
public class AdministrativoWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AdministrativoWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreAdministrativo = new javax.swing.JTextField();
        txtSegundoApellidoAdministrativo = new javax.swing.JTextField();
        txtTelefonoAdministrativo = new javax.swing.JTextField();
        txtClaveAdministrativo = new javax.swing.JTextField();
        btnActualizarAdministrativo = new javax.swing.JButton();
        btnEliminarAdministrativo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaAdministrativo = new javax.swing.JTextField();
        txtPrimerApellidoAdministrativo = new javax.swing.JTextField();
        btnSalirAdministrativo = new javax.swing.JButton();
        btnGuardarCambiosAdministrativo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 350));
        setPreferredSize(new java.awt.Dimension(550, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Personal Administrativo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setText("Primer Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setText("Segundo Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setText("Teléfono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setText("Clave:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtNombreAdministrativo.setName("txtNombreAdministrativo"); // NOI18N
        txtNombreAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAdministrativoActionPerformed(evt);
            }
        });
        txtNombreAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtNombreAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, -1));

        txtSegundoApellidoAdministrativo.setName("txtSegundoApellidoAdministrativo"); // NOI18N
        txtSegundoApellidoAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSegundoApellidoAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtSegundoApellidoAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, -1));

        txtTelefonoAdministrativo.setName("txtTelefonoAdministrativo"); // NOI18N
        txtTelefonoAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtTelefonoAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 220, -1));

        txtClaveAdministrativo.setName("txtClaveAdministrativo"); // NOI18N
        getContentPane().add(txtClaveAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 220, -1));

        btnActualizarAdministrativo.setText("Actualizar");
        btnActualizarAdministrativo.setName("btnActualizarAdministrativo"); // NOI18N
        btnActualizarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAdministrativoActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        btnEliminarAdministrativo.setText("Eliminar");
        btnEliminarAdministrativo.setName("btnEliminarAdministrativo"); // NOI18N
        btnEliminarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAdministrativoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 80, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 80, -1));

        jLabel8.setText("Cédula:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtCedulaAdministrativo.setName("txtCedulaAdministrativo"); // NOI18N
        txtCedulaAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtCedulaAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, -1));

        txtPrimerApellidoAdministrativo.setName("txtPrimerApellidoAdministrativo"); // NOI18N
        txtPrimerApellidoAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrimerApellidoAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtPrimerApellidoAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 220, -1));

        btnSalirAdministrativo.setText("Salir");
        btnSalirAdministrativo.setName("btnSalirAdministrativo"); // NOI18N
        btnSalirAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAdministrativoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        btnGuardarCambiosAdministrativo.setText("Guardar Cambios");
        btnGuardarCambiosAdministrativo.setName("btnGuardarCambiosAdministrativo"); // NOI18N
        btnGuardarCambiosAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosAdministrativoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCambiosAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAdministrativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAdministrativoActionPerformed

    private void txtNombreAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAdministrativoKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            txtNombreAdministrativo.setEditable(false);
        } else {
            txtNombreAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtNombreAdministrativoKeyPressed

    private void txtSegundoApellidoAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoApellidoAdministrativoKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            txtSegundoApellidoAdministrativo.setEditable(false);
        } else {
            txtSegundoApellidoAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtSegundoApellidoAdministrativoKeyPressed

    private void txtTelefonoAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoAdministrativoKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtTelefonoAdministrativo.setEditable(false);
        } else if (Character.isSpaceChar(c)) {
            txtTelefonoAdministrativo.setEditable(false);
        } else {
            txtTelefonoAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtTelefonoAdministrativoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNombre(txtNombreAdministrativo.getText());
        usuario.setPrimerApellido(txtPrimerApellidoAdministrativo.getText());
        usuario.setSegundoApellido(txtSegundoApellidoAdministrativo.getText());
        usuario.setIdentificacion(txtCedulaAdministrativo.getText());
        usuario.setClave(txtClaveAdministrativo.getText());
        usuario.setTelefono(txtTelefonoAdministrativo.getText());
        usuario.setTipoUsuario(TipoUsuario.ADMINISTRACION);
        Boolean guardado = Controlador.crearUsuario(usuario);
        JOptionPane.showMessageDialog(null, "Administrativo guardado con éxito");
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaAdministrativoKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtCedulaAdministrativo.setEditable(false);
        } else {
            txtCedulaAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtCedulaAdministrativoKeyPressed

    private void txtPrimerApellidoAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerApellidoAdministrativoKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            txtPrimerApellidoAdministrativo.setEditable(false);
        } else {
            txtPrimerApellidoAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtPrimerApellidoAdministrativoKeyPressed

    private void btnSalirAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAdministrativoActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirAdministrativoActionPerformed

    private void btnActualizarAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAdministrativoActionPerformed
        btnActualizarAdministrativo.setVisible(false);
        btnGuardar.setVisible(false);
        btnGuardarCambiosAdministrativo.setVisible(true);
        txtNombreAdministrativo.setEnabled(true);
        txtPrimerApellidoAdministrativo.setEnabled(true);
        txtSegundoApellidoAdministrativo.setEnabled(true);
        txtCedulaAdministrativo.setEnabled(true);
        txtTelefonoAdministrativo.setEnabled(true);
        txtClaveAdministrativo.setEnabled(true);

    }//GEN-LAST:event_btnActualizarAdministrativoActionPerformed
    public String usuarioid;
    private void btnGuardarCambiosAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosAdministrativoActionPerformed
        Usuario usuario = Controlador.obtenerUsuario(usuarioid);
        usuario.setNombre(txtNombreAdministrativo.getText());
        usuario.setPrimerApellido(txtPrimerApellidoAdministrativo.getText());
        usuario.setSegundoApellido(txtSegundoApellidoAdministrativo.getText());
        usuario.setIdentificacion(txtCedulaAdministrativo.getText());
        usuario.setClave(txtClaveAdministrativo.getText());
        usuario.setTelefono(txtTelefonoAdministrativo.getText());
        usuario.setTipoUsuario(TipoUsuario.ADMINISTRACION);
        Boolean guardado = Controlador.updateUsuario(usuario);
        if (guardado) {
            JOptionPane.showMessageDialog(null, "Administrativo actualizado");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar administrativo",
                    "Atención", JOptionPane.ERROR_MESSAGE);
        }

        dispose();
    }//GEN-LAST:event_btnGuardarCambiosAdministrativoActionPerformed

    private void btnEliminarAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAdministrativoActionPerformed
        /*Usuario Usuario = Controlador.obtenerUsuario(usuarioid);
        Boolean borrado = Controlador.borrarUsuario(usuarioid);
        if (borrado) {
            JOptionPane.showMessageDialog(null, "Encargado borrado con éxito");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error al borrar encargado",
                    "Atención", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_btnEliminarAdministrativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrativoWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarAdministrativo;
    public javax.swing.JButton btnEliminarAdministrativo;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnGuardarCambiosAdministrativo;
    private javax.swing.JButton btnSalirAdministrativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField txtCedulaAdministrativo;
    public javax.swing.JTextField txtClaveAdministrativo;
    public javax.swing.JTextField txtNombreAdministrativo;
    public javax.swing.JTextField txtPrimerApellidoAdministrativo;
    public javax.swing.JTextField txtSegundoApellidoAdministrativo;
    public javax.swing.JTextField txtTelefonoAdministrativo;
    // End of variables declaration//GEN-END:variables
}
