/*
 * Copyright (C) 2022 Julio
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package instituto.gui;

import instituto.data.controladdores.Controlador;
import instituto.data.modelos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio
 */
public class AdministrativoWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AdministrativoWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreAdministrativo = new javax.swing.JTextField();
        txtSegundoApellidoAdministrativo = new javax.swing.JTextField();
        txtTelefonoAdministrativo = new javax.swing.JTextField();
        txtClaveAdministrativo = new javax.swing.JTextField();
        cbxRolAdministrativo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaAdministrativo = new javax.swing.JTextField();
        txtPrimerApellidoAdministrativo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Personal Administrativo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setText("Rol:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setText("Primer Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setText("Segundo Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setText("Teléfono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setText("Clave:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtNombreAdministrativo.setName("txtNombreAdministrativo"); // NOI18N
        txtNombreAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAdministrativoActionPerformed(evt);
            }
        });
        txtNombreAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtNombreAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, -1));

        txtSegundoApellidoAdministrativo.setName("txtSegundoApellidoAdministrativo"); // NOI18N
        txtSegundoApellidoAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSegundoApellidoAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtSegundoApellidoAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, -1));

        txtTelefonoAdministrativo.setName("txtTelefonoAdministrativo"); // NOI18N
        txtTelefonoAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtTelefonoAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 220, -1));

        txtClaveAdministrativo.setName("txtClaveAdministrativo"); // NOI18N
        getContentPane().add(txtClaveAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 220, -1));

        cbxRolAdministrativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrativo", "Profesor", "Seguridad", "Miscelaneo" }));
        cbxRolAdministrativo.setName("cbxRolAdministrativo"); // NOI18N
        getContentPane().add(cbxRolAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 150));

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jButton2.setText("Actualizar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jButton3.setText("Eliminar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel8.setText("Cédula:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtCedulaAdministrativo.setName("txtCedulaAdministrativo"); // NOI18N
        txtCedulaAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtCedulaAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, -1));

        txtPrimerApellidoAdministrativo.setName("txtPrimerApellidoAdministrativo"); // NOI18N
        txtPrimerApellidoAdministrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrimerApellidoAdministrativoKeyPressed(evt);
            }
        });
        getContentPane().add(txtPrimerApellidoAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAdministrativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAdministrativoActionPerformed

    private void txtNombreAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAdministrativoKeyPressed
        char c =evt.getKeyChar();
        if(Character.isDigit(c))
        {
            txtNombreAdministrativo.setEditable(false);
        }else
        {
            txtNombreAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtNombreAdministrativoKeyPressed

    private void txtSegundoApellidoAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoApellidoAdministrativoKeyPressed
        char c =evt.getKeyChar();
        if(Character.isDigit(c))
        {
            txtNombreAdministrativo.setEditable(false);
        }else
        {
            txtNombreAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtSegundoApellidoAdministrativoKeyPressed

    private void txtTelefonoAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoAdministrativoKeyPressed
        char c =evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtTelefonoAdministrativo.setEditable(false);
        } else if (Character.isSpaceChar(c))
        {
            txtTelefonoAdministrativo.setEditable(false);
        }else
        {
            txtTelefonoAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtTelefonoAdministrativoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNombre(txtNombreAdministrativo.getText());
        usuario.setPrimerApellido(txtPrimerApellidoAdministrativo.getText());
        usuario.setSegundoApellido(txtSegundoApellidoAdministrativo.getText());
        usuario.setIdentificacion(txtCedulaAdministrativo.getText());
        usuario.setClave(txtClaveAdministrativo.getText());
        usuario.setTelefono(txtTelefonoAdministrativo.getText());
        //usuario.setTipoUsuario(String.valueOf(cbxRolAdministrativo.getSelectedIndex()));
        // falta agregar el tipo de usuario que es el administrativo.
        Boolean guardado = Controlador.crearUsuario(usuario);
        JOptionPane.showMessageDialog(null, "Administrativo guardado con éxito");
            dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaAdministrativoKeyPressed
        char c =evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtCedulaAdministrativo.setEditable(false);
        }else
        {
            txtCedulaAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtCedulaAdministrativoKeyPressed

    private void txtPrimerApellidoAdministrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerApellidoAdministrativoKeyPressed
        char c =evt.getKeyChar();
        if(Character.isDigit(c))
        {
            txtNombreAdministrativo.setEditable(false);
        }else
        {
            txtNombreAdministrativo.setEditable(true);
        }
    }//GEN-LAST:event_txtPrimerApellidoAdministrativoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrativoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrativoWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxRolAdministrativo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCedulaAdministrativo;
    private javax.swing.JTextField txtClaveAdministrativo;
    private javax.swing.JTextField txtNombreAdministrativo;
    private javax.swing.JTextField txtPrimerApellidoAdministrativo;
    private javax.swing.JTextField txtSegundoApellidoAdministrativo;
    private javax.swing.JTextField txtTelefonoAdministrativo;
    // End of variables declaration//GEN-END:variables
}
